In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/IMDB Dataset - IMDB Dataset.csv",encoding='utf-8',on_bad_lines='skip')

In [ ]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [ ]:
# if i want convert all movie review into lowercase then
df['review']=df['review'].str.lower()

In [ ]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
import re
def remove_html_tags(text):
  Pattern=re.compile('<.*?>')
  return Pattern.sub(r'',text)

In [ ]:
text="<html><body><p> m=Movie1 </p> Click here to <a heref='http://goggle.com'>download/a"

In [ ]:
remove_html_tags(text)

' m=Movie1  Click here to download/a'

In [ ]:
df['review']=df['review'].apply(remove_html_tags)

In [ ]:
def remove_url(text):
  Pattern=re.compile(r'http?://\s+|www\.\s+')
  return Pattern.sub(r'',text)

In [ ]:
text4='for notebook click http://www.deture.com/delta/note1234acc'

In [ ]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude=string.punctuation

In [ ]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
    return text

In [ ]:
text3='string.with.punctuation?'

In [ ]:
remove_punc(text3)

'string.with.punctuation?'

In [ ]:
df['review']=df['review'].apply(remove_punc)

In [ ]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
# chatword treatment

In [ ]:
chat_words={'u2':'You too','BBL':'Be Back Later','GAL':'Get A life'}

In [ ]:
chat_words

{'u2': 'You too', 'BBL': 'Be Back Later', 'GAL': 'Get A life'}

In [ ]:
def chat_conversion(text):
  new_text=[]
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
      return "".join(new_text)

In [ ]:
chat_conversion('BBL')

In [ ]:
chat_words

{'u2': 'You too', 'BBL': 'Be Back Later', 'GAL': 'Get A life'}

In [ ]:
#spelling correction

In [ ]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

In [ ]:
from textblob import TextBlob

In [ ]:
Incorrect_text='ceertain conditionas sevral ggeneration aree modifieed in the saame manner'
textBlb=TextBlob(Incorrect_text)
textBlb.correct().string

'certain conditions several generation are modified in the same manner'

In [ ]:
# removing step words

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
STOPWORDS=set(stopwords.words('english'))

In [ ]:
# stopwords

In [ ]:
def remove_stopwords(text):
  new_text=[]
  for word in text.split():
    if word in set(stopwords.words('english')):
      new_text.append('')
    else:
      new_text.append(word)
  x=new_text[:]
  new_text.clear()
  return "".join(x)
remove_stopwords('probably my all-time favorite movie,a story of selfness, sacrifice and dedication to a nobel causes.')

'probablyall-timefavoritemovie,astoryselfness,sacrificededicationnobelcauses.'