In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")

In [ ]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.56  -0.82  -1.17
25%    -0.94   -0.84  -0.51  -0.82  -1.17
50%    -0.04   -0.84   0.01  -0.82  -0.27
75%     0.91    1.19   0.53   1.22   0.63
max     1.69    1.19   1.57   1.22   1.53

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,y_pred)

0.55

In [ ]:
ds=pd.read_csv("/content/titanic - titanic.csv")

In [ ]:
ds['Age']=ds['Age'].fillna(ds['Age'].mean())

In [ ]:
ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [ ]:
ds=ds.drop(columns=['PassengerId','Name','Cabin','Embarked','Ticket','Sex'])

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [ ]:
x=ds.drop(columns=['Survived'])
y=ds['Survived']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

       Pclass     Age   SibSp   Parch    Fare
count  334.00  334.00  334.00  334.00  333.00
mean     0.00   -0.00    0.00   -0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00
min     -1.50   -2.30   -0.50   -0.43   -0.64
25%     -1.50   -0.58   -0.50   -0.43   -0.50
50%      0.87    0.01   -0.50   -0.43   -0.39
75%      0.87    0.37    0.56   -0.43   -0.08
max      0.87    3.54    7.98    9.19    8.20

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train, y_train)

ValueError: Input X contains NaN.
KNeighborsClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,y_pred)

0.5595238095238095

In [ ]:
dc=pd.read_csv("/content/Churn_Modelling - Churn_Modelling.csv")