In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv("/content/Social_Network_Ads - Social_Network_Ads.csv")

In [ ]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df=df.drop(columns=['User ID','Gender'])

In [ ]:
x=df.drop(columns=['Purchased'],axis=1)
y=df['Purchased']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('PCA',PCA(n_components=2)),
    ('classifier',RandomForestClassifier(n_estimators=100,random_state=42)),
])

In [ ]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('PCA', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('PCA', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
y_pred=pipe.predict(x_test)

In [ ]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.8875

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
dc=pd.read_csv("/content/covid_toy - covid_toy.csv")

In [ ]:
dc

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
dc =dc.drop(columns=['city','gender','cough'])

In [ ]:
x=dc.drop(columns=['has_covid'],axis=1)
y=dc['has_covid']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])
pipe

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
y_pred=pipe.predict(x_test)

In [ ]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.5

In [ ]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
du=pd.read_csv("/content/userbehaviour - userbehaviour.csv")

In [ ]:
du

,userid,Average Screen Time,Average Spent on App (INR),Left Review,Ratings,New Password Request,Last Visited Minutes,Status
0,1001,17,634,1,9,7,2990,Installed
1,1002,0,54,0,4,8,24008,Uninstalled
2,1003,37,207,0,8,5,971,Installed
3,1004,32,445,1,6,2,799,Installed
4,1005,45,427,1,5,6,3668,Installed
...,...,...,...,...,...,...,...,...
994,1995,38,938,0,5,4,1865,Installed
995,1996,43,61,0,6,8,1327,Installed
996,1997,47,761,0,6,1,1936,Installed
997,1998,6,73,1,5,1,3436,Installed
998,1999,9,54,0,4,2,4039,Installed

In [ ]:
X = du.drop(columns=['Status','userid'])
y = du['Status']

In [ ]:
print("Before SMOTE:")
print(y.value_counts())

Before SMOTE:
Status
Installed      916
Uninstalled     83
Name: count, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(x_train, y_train)

In [ ]:
print("After SMOTE:")
print(y_train_res.value_counts())

After SMOTE:
Status
Installed      729
Uninstalled    729
Name: count, dtype: int64

In [ ]:
balanced_df = pd.concat([pd.DataFrame(X_train_res), pd.DataFrame(y_train_res,
                                                                 columns=['Status'])],
                        axis=1)

print(balanced_df.head())

   Average Screen Time  Average Spent on App (INR)  Left Review  Ratings  \
0                   21                         892            0        7
1                   30                         416            0        5
2                   29                          91            1        7
3                   22                         706            0        9
4                   16                         767            1        8

   New Password Request  Last Visited Minutes     Status
0                     7                  4942  Installed
1                     4                  2998  Installed
2                     8                  3241  Installed
3                     4                  4851  Installed
4                     5                  2602  Installed

In [ ]:
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

In [ ]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
pipe.fit(X_train_res, y_train_res)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
y_pred=pipe.predict(x_test)

In [ ]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.995